### ISSUE TITLE
import error, please help!

### ISSUE THREAD

**Issue by lk1983823** [yuanming-hu/difftaichi#3]
Ubuntu 16.04
Anaconda 3.5.0.1
cuda 10.0

I have pip installed the package into a anaconda pyenv. But when I import taichi, it shows:

`[Release mode]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.main import main
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames, mp4_to_gif, scale_video, crop_video, accelerate_video
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/tools/video.py", line 3, in <module>
    import taichi.core as core
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import tc_core, build, format, load_module, start_memory_monitoring, \
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/core/util.py", line 158, in <module>
    import_tc_core()
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/core/util.py", line 31, in import_tc_core
    import taichi_core as core
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/core/../lib/taichi_core.so)
`

How can I fix it ? Thanks!

**Comment by zdx3578** [comment]
(tmtaiji) ➜  examples git:(master) python rigid_body.py 
[Release mode]
Traceback (most recent call last):
  File "rigid_body.py", line 3, in <module>
    import taichi as ti
  File "/home/zdx/tmtaiji/lib/python3.7/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.main import main
  File "/home/zdx/tmtaiji/lib/python3.7/site-packages/taichi/main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames, mp4_to_gif, scale_video, crop_video, accelerate_video
  File "/home/zdx/tmtaiji/lib/python3.7/site-packages/taichi/tools/video.py", line 3, in <module>
    import taichi.core as core
  File "/home/zdx/tmtaiji/lib/python3.7/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import tc_core, build, format, load_module, start_memory_monitoring, \
  File "/home/zdx/tmtaiji/lib/python3.7/site-packages/taichi/core/util.py", line 158, in <module>
    import_tc_core()
  File "/home/zdx/tmtaiji/lib/python3.7/site-packages/taichi/core/util.py", line 31, in import_tc_core
    import taichi_core as core
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/zdx/tmtaiji/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so)
(tmtaiji) ➜  examples git:(master)

**Comment by zdx3578** [comment]
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-7 g++-7
gcc-7 --version
